#ifndef _MOS_RISCV_SYSCALL_H_
#define _MOS_RISCV_SYSCALL_H_

enum {
	SYS_putchar = 0,
	SYS_print_cons = 1,
	SYS_getenvid = 2,
	SYS_yield = 3,
	SYS_env_destroy = 4,
	SYS_set_tlb_mod_entry = 5,
	SYS_mem_alloc = 6,
	SYS_mem_map = 7,
	SYS_mem_unmap = 8,
	SYS_exofork = 9,
	SYS_env_set_status = 10,
	SYS_set_trapframe = 11,
	SYS_panic = 12,
	SYS_ipc_try_send = 13,
	SYS_ipc_recv = 14,
	SYS_cgetc = 15,
	SYS_write_dev = 16,
	SYS_read_dev = 17,
	SYS_fs_open = 18,
	SYS_fs_read = 19,
	SYS_fs_close = 20,
	SYS_fs_stat = 21,
	SYS_fs_seek = 22,
	SYS_fs_write = 23,
	SYS_spawn = 24,
	SYS_fs_unlink = 25,
	SYS_fs_rename = 26,
	SYS_fs_list = 27,
	SYS_fork = 28,
	SYS_page_info = 29,
	SYS_mem_protect = 30,
	SYS_page_next = 31,
	SYS_env_status = 32,
	SYS_fs_fstat = 33,
	SYS_fs_dup = 34,
	SYS_fs_truncate = 35,
	SYS_ipc_info = 36,
	SYS_pipe = 37,
	SYS_fs_mkdir = 38,
	SYS_fs_sync = 39,
	SYS_env_find = 40,
	SYS_block_read = 41,
	SYS_block_write = 42,
	SYS_fs_chmod = 43,
	MAX_SYSNO,
};

void syscall_dispatch(void);
void syscall_init(void);

#endif
